# @package _global_

datamodule:
  slice_win: 
    lat: 200
    lon: 200
    time: ${params.dT}
  strides: 
    lat: 200
    lon: 200
    time: 1
params:
  patch_weight:
    _target_: lit_model_augstate.get_constant_crop
    patch_size: ${datamodule.slice_win}
    crop: 
      lat: 0
      lon: 0
      time: 2

defaults:
  - /domain@datamodule.dim_range: natl
  - /domain@params.test_domain: natl
