# @package _global_

# Ici tu peux surcharger les parties de la config que tu veux sans impacter les autres, par exemple:

entrypoint:
   weights_save_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GFMMexp240x240_ChckPt-wSST-hydra-exp/'
   
# ####################
# Models considered in JAMES submission
   ckpt_path: '../TrainedModels/modelUVwSSTGF-unet1_050-augdata-augstate-dT07-sstobs-nolinear-tanh-bn_20-nowgeo-nostrain-grad_05_03_150-epoch=84-val_loss=0.9944.ckpt'
#   ckpt_path: '../TrainedModels/modelUVwSSTGF-unet1_050-augdata-dws02-augstate-dT07-nowgeo-nostrain-grad_05_03_150-epoch=05-val_loss=2.4105.ckpt'
#   ckpt_path: '../TrainedModels/modelUVwSSTGF-unet1_050-augdata-DirectInv-dT07-nostrain-epoch=13-val_loss=4.0956.ckpt'
#   ckpt_path: '../TrainedModels/modelUVwSSTGF-unet1_050-augdata-DirectInv-wSST-dT07-nostrain-epoch=62-val_loss=2.5038.ckpt'
params:
  flag_update_training_config: False # True #  
  sst_model: 'nolinear-tanh-bn'#'nolinear-tanh-bn-att'  #'linear-bn'#''linear'# 
  files_cfg:
    oi_path: ${file_paths.oi_swot_4nadir} #  ${file_paths.oi_4nadir}  # 
    oi_var: ssh_mod
    obs_mask_path: ${file_paths.pseudo_obs} #  ${file_paths.pseudo_obs_4nadir} # 
    obs_mask_var: ssh_mod
    gt_path: ${file_paths.natl_ssh_daily}
    gt_var: ssh
  patch_weight:
    _target_: lit_model_uv.get_cropped_hanning_mask
    patch_size: ${datamodule.slice_win}
    crop:
      time: 3
  k_n_grad: 3
  n_grad: 5
  apha_grad_descent_step: 0.
  dT: 7
  DimAE: 50
  dim_obs_sst_feat: 2#10
  dim_grad_solver: 150
  save_rec_netcdf: True #False#
  sig_filter_laplacian: 1.
#  scale_dwscaling_sst: 1.
  sig_filter_div_diag: 1.
  path_save_netcdf: '/gpfsscratch/rech/yrf/ulh44ct/temp/save.ckpt'
  ckpt_name: 'modelUVwSSTGF-unet1-{epoch:02d}-{val_loss:.4f}'
datamodule:
  resize_factor: 1
defaults:
  - /xp/ronan/base_xp_uv
  - /splits/dc_boost_swot@datamodule
#  - /xp/xp_aug/aug/with_aug_state_uv
  - /xp/xp_aug/aug/with_mm_aug_state_uv
  - /xp/xp_aug/dl/d240_p240x5_s240x1
  - /xp/xp_aug/sst/with_sst
  - /xp/xp_aug/loss/map
  - /xp/xp_aug/train_strat/const_lr_ngrad_5_3cas
  - _self_ 
