# @package _global_

# Ici tu peux surcharger les parties de la config que tu veux sans impacter les autres, par exemple:

entrypoint:
   weights_save_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/SLANATL60_GFMMexp240x240_ChckPt-wSST-hydra-exp/'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/SLANATL60_GFMMexp240x240_ChckPt-wSST-hydra-exp/version_15/checkpoints/modelSLAwSSTGF-unet1_050-augdata-augstate-dT07-sstobs-linear_02-grad_05_03_150-epoch=141-val_loss=0.2899.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/SLANATL60_GFMMexp240x240_ChckPt-wSST-hydra-exp/version_3/checkpoints/modelSLAwSSTGF-unet1_050-augdata-DirectInv-dT07-epoch=196-val_loss=1.0252.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/SLANATL60_GFMMexp240x240_ChckPt-wSST-hydra-exp/version_7/checkpoints/modelSLAwSSTGF-unet-std_050-augdata-DirectInv-dT07-epoch=58-val_loss=1.0545.ckpt'
params:
  k_n_grad: 3
  n_grad: 0
  dT: 7
  DimAE: 50
  dim_grad_solver: 150
  phi_param: 'unet-std'#'unet1'
  ckpt_name: 'modelSLAwSSTGF-{epoch:02d}-{val_loss:.4f}'
  patch_weight:
    _target_: lit_model_augstate.get_cropped_hanning_mask
    patch_size: ${datamodule.slice_win}
    crop:
      time: 1
  val_diag_freq: 5 
  padding_mode: reflect
  alpha_mse_ssh: 50. # loss
  alpha_mse_gssh: 1000.
  norm_obs: l2
  norm_prior: l2
datamodule:
  aug_train_data: True

defaults:
  - /xp/xp_aug/base_xp
  - /splits/dc_boost_swot@datamodule
  - /xp/xp_aug/aug/without_aug_state
  - /xp/xp_aug/dl/d240_p240x5_s240x1
  - /xp/xp_aug/sst/without_sst
  - /xp/xp_aug/loss/map
  - /xp/xp_aug/train_strat/const_lr_ngrad_5_3cas
  - _self_ 
