# @package _global_

# Ici tu peux surcharger les parties de la config que tu veux sans impacter les autres, par exemple:

entrypoint:
   weights_save_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GFMMexp240x240_ChckPt-MRwoDUACS-hydra-exp/'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GFMMexp240x240_ChckPt-MRwoDUACS-hydra-exp/version_217/checkpoints/modelUVGF-MR-unet1_050-augdata-lr04-augstate-dT21-sstobs-nolinear-tanh-bn_20-nowgeo-nodivstrain-grad_05_03_150-epoch=61-val_loss=3.7559.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GFMMexp240x240_ChckPt-MRwoDUACS-hydra-exp/version_229/checkpoints/modelUVGF-MR_dw2-unet1_050-augdata-lr03-augstate-dT21-sstobs-nolinear-tanh-bn_20-nowgeo-nodivstrain-grad_05_03_150-epoch=127-val_loss=1.8120.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GFMMexp240x240_ChckPt-MRwoDUACS-hydra-exp/version_234/checkpoints/modelUVGF-MR_dw2-unet1_050-augdata-lr04-augstate-dT21-sstobs-nolinear-tanh-bn_20-nowgeo-nodivstrain-grad_05_03_150-epoch=38-val_loss=3.5322.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GFMMexp240x240_ChckPt-MRwoDUACS-hydra-exp/version_230/checkpoints/modelUVGF-MR_dw2-unet1_050-augdata-lr04-augstate-dT31-sstobs-nolinear-tanh-bn_20-nowgeo-nodivstrain-grad_05_03_150-epoch=79-val_loss=4.0784.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GFMMexp240x240_ChckPt-MRwoDUACS-hydra-exp/version_271/checkpoints/modelUVGF-MR_v2-unet1_050-augdata02-lr04-augstate-dT31-nowgeo-nodivstrain-grad_05_03_150-epoch=29-val_loss=5.8957.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GFMMexp240x240_ChckPt-MRwoDUACS-hydra-exp/version_287/checkpoints/modelUVGF-MR_v2-unet1_050-augdata02-lr04-augstate-dT31-nowgeo-nodivstrain-grad_05_01_02_01_150-epoch=73-val_loss=8.0220.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GFMMexp240x240_ChckPt-MRwoDUACS-hydra-exp/version_287/checkpoints/modelUVGF-MR_v2-unet1_050-augdata02-lr04-augstate-dT31-nowgeo-nodivstrain-grad_05_01_02_02_150-epoch=52-val_loss=8.0774.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GFMMexp240x240_ChckPt-MRwoDUACS-hydra-exp/version_290/checkpoints/modelUVGF-MR_v2-unet1_050-augdata02-lr04-augstate-dT31-nowgeo-nodivstrain-grad_05_01_02_02_150-epoch=02-val_loss=1.8835.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GFMMexp240x240_ChckPt-MRwoDUACS-hydra-exp/version_291/checkpoints/modelUVGF-MR_v2-unet1_050-augdata02-lr04-augstate-dT31-nowgeo-nodivstrain-grad_05_01_03_03_150-epoch=32-val_loss=2.5157.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GFMMexp240x240_ChckPt-MRwoDUACS-hydra-exp/version_296/checkpoints/modelUVGF-MR_v4-unet1_050-augdata02-lr04-augstate-dT31-nowgeo-nodivstrain-grad_05_02_02_01_150-epoch=61-val_loss=0.8663.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GFMMexp240x240_ChckPt-MRwoDUACS-hydra-exp/version_297/checkpoints/modelUVGF-MR_v4-unet1_050-augdata02-lr04-augstate-dT31-nowgeo-nodivstrain-grad_05_01_02_02_150-epoch=36-val_loss=2.0500.ckpt'
   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GFMMexp240x240_ChckPt-MRwoDUACS-hydra-exp/version_297/checkpoints/modelUVGF-MR_v4-unet1_050-augdata02-lr04-augstate-dT31-nowgeo-nodivstrain-grad_05_04_03_01_150-epoch=04-val_loss=0.8692.ckpt'
lit_mod_cls: lit_model_uv_mr_wo_duacs_v2.LitModelUV
params:
  flag_update_training_config: True # False # 
  sst_model: 'nolinear-tanh-bn'#'nolinear-tanh-bn-att'#''linear-bn'#'linear' #
  n_fourdvar_iter_lr: ??
  n_fourdvar_iter_hr: ??
  n_fourdvar_iter: ??
  n_grad: 5
  dT: ??
  scale_lr: 4
  use_init_lr_from_hr: False
  dT_hr_model: 7 
  DimAE: 50
  dim_obs_sst_feat: 20
  dim_grad_solver: 150
  phi_param: 'unet1'#'unet-std'#
  ckpt_name: 'modelUVGF-MR_v4-{epoch:02d}-{val_loss:.4f}' #'modelUVwSSTGF-{epoch:02d}-{val_loss:.4f}'
  use_sst_obs: False # True # 
  use_sst_state: False # True # 
  patch_weight:
    _target_: lit_model_uv_mr_wo_duacs_v2.get_cropped_hanning_mask_ronan
    patch_size: ${datamodule.slice_win}
    crop:
      time: 5
  val_diag_freq: 2 
  padding_mode: reflect
  residual_wrt_geo_velocities: 0 #False #
  type_div_train_loss: 1
  alpha_mse_ssh: 50. # loss
  alpha_mse_gssh: 1000.
  alpha_mse_uv: 10. #50.
  alpha_mse_uv_geo: 0.
  alpha_mse_div: 0. # 1000. #5 0. # 00. # 100. 
  alpha_mse_strain: 0. #1000.
  alpha_loss_lr: 1.
  alpha_loss_hr: 0.1  
  sig_filter_div: 1.
  norm_obs: l2
  norm_prior: l2
  sampling_model: 'sampling-from-sst'
  nb_feat_sampling_operator: 0
  alpha_sampling_uv: 10.
  thr_l1_sampling_uv: 0.10
  scale_dwscaling_sst: 1.
  aug_train_data: 2
datamodule:
  resize_factor: 1
  aug_train_data: ${params.aug_train_data}  
  use_auto_padding: False
defaults:
  - /xp/ronan/base_xp_uv
  - /splits/dc_boost_swot@datamodule
  - /xp/xp_aug/aug/with_aug_state_uv_mr_wo_duacs
#  - /xp/xp_aug/aug/with_mm_aug_state_uv
  - /xp/xp_aug/dl/d240_p240x5_s240x1
  - /xp/xp_aug/sst/with_sst
  - /xp/xp_aug/loss/map
  - /xp/xp_aug/train_strat/const_lr_ngrad_5_3cas
  - _self_ 
