# @package _global_

# Ici tu peux surcharger les parties de la config que tu veux sans impacter les autres, par exemple:

entrypoint:
   weights_save_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_Eodyn_ChckPt-wSST-hydra-exp/'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GFMMexp240x240_ChckPt-wSST-hydra-exp/version_313/checkpoints/modelUVwSSTGF-v2-unet1_050-augdata-augstate-dT07-nowgeo-nodivstrain-grad_05_03_150-epoch=75-val_loss=2.2945.ckpt'
   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_Eodyn_ChckPt-wSST-hydra-exp/version_14/checkpoints/modelUVwSSTGF-eodyn-unet1_050-augdata-augstate-dT07-sstobs-nolinear-tanh-bn_20-nowgeo-nodivstrain-grad_05_03_150-epoch=95-val_loss=1.4261.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_Eodyn_ChckPt-wSST-hydra-exp/version_13/checkpoints/modelUVwSSTGF-eodyn-unet1_050-augdata-augstate-dT07-nowgeo-nodivstrain-grad_05_03_150-epoch=31-val_loss=3.2470.ckpt'
params:
  flag_update_training_config: False # True #  
  sst_model: 'nolinear-tanh-bn'#'nolinear-tanh-bn-att'#''linear-bn'#'linear' #
  k_n_grad: 3
  n_grad: 5
  apha_grad_descent_step: 0.
  learn_fsgd_param: false #true
  dT: 7
  scale_dwscaling : 1.
  DimAE: 50
  dim_obs_sst_feat: 20
  dim_grad_solver: 150
  phi_param: 'unet1'#'unet-std'#
  ckpt_name: 'modelUVwSSTGF-eodyn-{epoch:02d}-{val_loss:.4f}' #'modelUVwSSTGF-{epoch:02d}-{val_loss:.4f}'
  use_sst_obs: ??#False #  True # 
  use_sst_state: False # True # 
  patch_weight:
    _target_: lit_model_uv.get_cropped_hanning_mask
    patch_size: ${datamodule.slice_win}
    crop:
      time: 1
  val_diag_freq: 5 
  padding_mode: reflect
  residual_wrt_geo_velocities: 0 #False #
  type_div_train_loss: 1
  alpha_mse_ssh: 50. # loss
  alpha_mse_gssh: 0. #1000.
  alpha_mse_uv: 50.
  alpha_mse_uv_geo: 10.
  alpha_mse_div: 0. #?? #1000. #0. # 5 0. # 00. # 100. 
  alpha_mse_strain: 0. # 1000. # 0. #
  sig_filter_div: 1.
  norm_obs: l2
  norm_prior: l2
  sampling_model: 'sampling-from-sst'
  nb_feat_sampling_operator: 0
  alpha_sampling_uv: 10.
  thr_l1_sampling_uv: 0.10
  scale_dwscaling_sst: 1.
datamodule:
  dl_kwargs:
    batch_size: 2
  aug_train_data: True 
  resize_factor: 1
defaults:
  - /xp/ronan/base_xp_uv
  - /splits/dc_boost_swot@datamodule
  - /xp/xp_aug/aug/with_aug_state_uv
#  - /xp/xp_aug/aug/with_mm_aug_state_uv
#  - /xp/xp_aug/dl/d240_p240x5_s240x1
  - /xp/xp_aug/dl/d120_p240x5_s240x1
  - /xp/xp_aug/sst/with_sst
  - /xp/xp_aug/loss/map
  - /xp/xp_aug/train_strat/const_lr_ngrad_5_3cas
  - _self_ 
