# @package _global_

# Ici tu peux surcharger les parties de la config que tu veux sans impacter les autres, par exemple:

entrypoint:
   weights_save_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GF_noDUACS40x240_ChckPt-wSST-hydra-exp/'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GF_noDUACS40x240_ChckPt-wSST-hydra-exp/version_146/checkpoints/modelUVwSSTGF_woDUACS-unet1_050-augdata-dws02-augstate-dT07-sstobs-nolinear-tanh-bn_20-nowgeo-nodivstrain-grad_05_03_150-epoch=197-val_loss=1.4766.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GF_noDUACS40x240_ChckPt-wSST-hydra-exp/version_146/checkpoints/modelUVwSSTGF_woDUACS-unet1_050-augdata-dws02-augstate-dT31-sstobs-nolinear-tanh-bn_20-nowgeo-nodivstrain-grad_05_03_150-epoch=117-val_loss=2.3523.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GF_noDUACS40x240_ChckPt-wSST-hydra-exp/version_146/checkpoints/modelUVwSSTGF_woDUACS-unet1_050-augdata-dws02-augstate-dT21-sstobs-nolinear-tanh-bn_20-nowgeo-nodivstrain-grad_05_03_150-epoch=93-val_loss=2.0468.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GF_noDUACS40x240_ChckPt-wSST-hydra-exp/version_148/checkpoints/modelUVwSSTGF_woDUACS-unet1_050-augdata-dws02-augstate-dT11-nowgeo-nodivstrain-grad_05_03_150-epoch=15-val_loss=2.6993.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GF_noDUACS40x240_ChckPt-wSST-hydra-exp/version_165/checkpoints/modelUVwSSTGF_woDUACS-unet1_050-augdata-dws02-augstate-dT31-sstobs-nolinear-tanh-bn_20-nowgeo-nodivstrain-grad_05_03_150-epoch=111-val_loss=1.2686.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GF_noDUACS40x240_ChckPt-wSST-hydra-exp/version_163/checkpoints/modelUVwSSTGF_woDUACS-unet1_050-augdata-dws02-augstate-dT31-nowgeo-nodivstrain-grad_05_03_150-epoch=66-val_loss=3.0296.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GF_noDUACS40x240_ChckPt-wSST-hydra-exp/version_232/checkpoints/modelUVwSSTGF_woDUACS-unet1_050-augdata-dws02-augstate-dT31-sstobs-nolinear-tanh-bn_20-nowgeo-nodivstrain-grad_05_03_150-epoch=177-val_loss=1.2300.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GF_noDUACS40x240_ChckPt-wSST-hydra-exp/version_244/checkpoints/modelUVwSSTGF-nouv-woDUACS-unet1_050-augdata-dws04-augstate-dT31-nowgeo-nodivstrain-grad_05_03_150-epoch=08-val_loss=0.9272.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GF_noDUACS40x240_ChckPt-wSST-hydra-exp/version_246/checkpoints/modelUVwSSTGF-nouv-woDUACS-unet1_050-augdata02-dws02-augstate-dT31-nowgeo-nodivstrain-grad_05_03_150-epoch=57-val_loss=0.5887.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GF_noDUACS40x240_ChckPt-wSST-hydra-exp/version_248/checkpoints/modelUVwSSTGF-woDUACS-unet1_050-augdata02-dws02-augstate-dT31-nowgeo-nodivstrain-grad_05_03_150-epoch=27-val_loss=2.8797.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GF_noDUACS40x240_ChckPt-wSST-hydra-exp/version_246/checkpoints/modelUVwSSTGF-nouv-woDUACS-unet1_050-augdata02-augstate-dT31-nowgeo-nodivstrain-grad_05_03_150-epoch=37-val_loss=0.6518.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GF_noDUACS40x240_ChckPt-wSST-hydra-exp/version_265/checkpoints/modelUVwSSTGF-woDUACS-phiOI-unet1_050-augdata02-dws02-augstate-dT31-nowgeo-nodivstrain-grad_05_03_150-epoch=14-val_loss=1.2408.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GF_noDUACS40x240_ChckPt-wSST-hydra-exp/version_262/checkpoints/modelUVwSSTGF-woDUACS-phiOI-unet1_050-augdata02-nouv-dws02-augstate-dT31-nowgeo-nodivstrain-grad_05_03_150-epoch=94-val_loss=0.5140.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GF_noDUACS40x240_ChckPt-wSST-hydra-exp/version_267/checkpoints/modelUVwSSTGF-woDUACS-phiorig-unet1_050-augdata02-dws02-augstate-dT31-nowgeo-nodivstrain-grad_05_03_150-epoch=15-val_loss=1.1174.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GF_noDUACS40x240_ChckPt-wSST-hydra-exp/version_268/checkpoints/modelUVwSSTGF-woDUACS-phiorig-unet1_050-augdata02-nouv-dws02-augstate-dT31-nowgeo-nodivstrain-grad_05_03_150-epoch=19-val_loss=0.6633.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GF_noDUACS40x240_ChckPt-wSST-hydra-exp/version_263/checkpoints/modelUVwSSTGF-woDUACS-phiOI-unet1_050-augdata02-dws02-augstate-dT31-nowgeo-nodivstrain-grad_05_03_150-epoch=96-val_loss=0.8398.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GF_noDUACS40x240_ChckPt-wSST-hydra-exp/version_274/checkpoints/modelUV-woDUACS-phiOI-unet1_050-augdata02-nouv-augstate-dT31-nowgeo-nodivstrain-grad_05_03_150-epoch=15-val_loss=0.9733.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GF_noDUACS40x240_ChckPt-wSST-hydra-exp/version_274/checkpoints/modelUV-woDUACS-phiOI-unet1_050-augdata02-nouv-augstate-dT31-nowgeo-nodivstrain-grad_05_03_150-epoch=49-val_loss=0.6918.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GF_noDUACS40x240_ChckPt-wSST-hydra-exp/version_340/checkpoints/modelUV-woDUACS-phiOI-unet1_050-augdata04-nouv-augstate-dT31-sstobs-nolinear-tanh-bn_20_19-nowgeo-nodivstrain-grad_05_03_150-epoch=31-val_loss=0.2675.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GF_noDUACS40x240_ChckPt-wSST-hydra-exp/version_345/checkpoints/modelUV-woDUACS-phiOI-unet1_050-augdata01-augstate-dT31-sstobs-nolinear-tanh-bn_20_31-nowgeo-nodivstrain-grad_05_03_150-epoch=153-val_loss=0.8756.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GF_noDUACS40x240_ChckPt-wSST-hydra-exp/version_348/checkpoints/modelUV-woDUACS-phiOI-unet1_050-augdata04-augstate-dT31-sstobs-nolinear-tanh-bn_20_31-nowgeo-nodivstrain-grad_05_03_150-epoch=134-val_loss=0.9073.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GF_noDUACS40x240_ChckPt-wSST-hydra-exp/version_352/checkpoints/modelUV-woDUACS-phiOI-unet1_050-augdata01-augstate-dT31-sstobs-nolinear-tanh-bn_20_31-nowgeo-nodivstrain-grad_05_03_150-epoch=106-val_loss=0.7641.ckpt'
   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GF_noDUACS40x240_ChckPt-wSST-hydra-exp/version_352/checkpoints/modelUV-woDUACS-phiOI-unet1_050-augdata01-augstate-dT31-sstobs-nolinear-tanh-bn_20_31-nowgeo-nostrain-grad_05_03_150-epoch=71-val_loss=0.8825.ckpt''
params:
  flag_update_training_config: True # False # 
  files_cfg:
    oi_path: ${file_paths.oi_swot_4nadir} #  ${file_paths.oi_4nadir}  # 
    oi_var: ssh_mod
    obs_mask_path: ${file_paths.pseudo_obs} #  ${file_paths.pseudo_obs_4nadir} # 
    obs_mask_var: ssh_mod
    gt_path: ${file_paths.natl_ssh_daily}
    gt_var: ssh
  sst_model: 'nolinear-tanh-bn'#'nolinear-tanh-bn-att'#''linear-bn'#'linear' #
  k_n_grad: 3
  n_grad: 5
  dT: 31
  scale_dwscaling : 1
  DimAE: 50
  dim_obs_sst_feat: 20
  dim_grad_solver: 150
  phi_param: 'unet1'#'unet-std'#
  ckpt_name: 'modelUV-woDUACS-phiOI-{epoch:02d}-{val_loss:.4f}'  #'modelUVwSSTGF-woDUACS-phiOI-{epoch:02d}-{val_loss:.4f}' #'modelUVwSSTGF-{epoch:02d}-{val_loss:.4f}'
  use_sst_obs: True #  False # 
  dt_sst_obs: ??
  use_sst_state: False # True # 
  patch_weight:
    _target_: lit_model_uv_wo_duacs.get_cropped_hanning_mask_ronan
    patch_size: ${datamodule.slice_win}
    crop:
      time: 5
  val_diag_freq: 5 
  padding_mode: reflect
  residual_wrt_geo_velocities: 0 #False #
  type_div_train_loss: 1
  alpha_mse_ssh: 50. # loss
  alpha_mse_gssh: 0. #1000.
  alpha_mse_uv: 50. # 10. #50.
  alpha_mse_uv_geo: 25. # 
  alpha_mse_div: 1000. # 0. # 500. # 100. 
  alpha_mse_strain: 0. #1000.
  sig_filter_div: 1.
  norm_obs: l2
  norm_prior: l2
  sampling_model: 'sampling-from-sst'
  nb_feat_sampling_operator: 0
  alpha_sampling_uv: 10.
  thr_l1_sampling_uv: 0.10
  aug_train_data: 1
datamodule:
  resize_factor: 1
  aug_train_data: ${params.aug_train_data}  
defaults:
  - /xp/ronan/base_xp_uv_wo_duacs
  - /splits/dc_boost_swot@datamodule
#  - /xp/xp_aug/aug/with_state_uv_wo_duacs
  - /xp/xp_aug/aug/with_aug_state_uv_wo_duacs
#  - /xp/xp_aug/aug/with_mm_aug_state_uv_wo_duacs
  - /xp/xp_aug/dl/d240_p240x5_s240x1
  - /xp/xp_aug/sst/with_sst
  - /xp/xp_aug/loss/map
  - /xp/xp_aug/train_strat/const_lr_ngrad_5_3cas
  - _self_ 
