# @package _global_
entrypoint:
   weights_save_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/MLDNATL60_GFMMexp240x240_ChckPt-wSST-hydra-exp/'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/MLDNATL60_GFMMexp240x240_ChckPt-wSST-hydra-exp/version_86/checkpoints/modelMLDwSSTGF-v2-resize02-DirectInv-wSST-dT21-epoch=09-val_loss=0.1391.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/MLDNATL60_GFMMexp240x240_ChckPt-wSST-hydra-exp/version_93/checkpoints/modelMLDwSSTGF-v2-resize02-augstate-dT21-mmstate-augstate-dT21-sstobs-nolinear-mld_05-grad_05_03_150-epoch=19-val_loss=0.1186.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/MLDNATL60_GFMMexp240x240_ChckPt-wSST-hydra-exp/version_99/checkpoints/modelMLDwSSTGF-v2-unet1_050-augdata-obsmld_10-resize02-DirectInv-wSST-dT21-epoch=174-val_loss=0.1507.ckpt'
params:
  flag_update_training_config: False #  
  mld_model: 'nolinear-mld'#'nolinear-tanh-bn'#''linear-bn'#'linear' #
  k_n_grad: 3
  n_grad: ??
  apha_grad_descent_step: 0.
  learn_fsgd_param: false #true
  dT: ??
  scale_dwscaling : 1.
  DimAE: 50
  dim_obs_sst_feat: 5
  dim_grad_solver: 150
  phi_param: ??#'unet-mld-mm'#unet1'# 'unet-std'#'
  ckpt_name: 'modelMLDwSSTGF-v2-{epoch:02d}-{val_loss:.4f}' #'modelUVwSSTGF-{epoch:02d}-{val_loss:.4f}'
  use_sst_obs: False # True #   
  use_sst_state: True # False #  
  patch_weight:
    _target_: lit_model_mld.get_cropped_hanning_mask
    patch_size: ${datamodule.slice_win}
    crop:
      time: 1
  val_diag_freq: 5 
  padding_mode: reflect
  type_div_train_loss: 1
  alpha_mse_ssh: ?? #1. # loss
  alpha_mse_gssh: 0. #0. #1000.
  alpha_mse_mld: 1. #1.
  norm_obs: l2
  norm_prior: l2
  sampling_model: 'sampling-from-sst'
  nb_feat_sampling_operator: 0
  num_mld_obs: ?? #10
  alpha_sampling_mld: 10.
  thr_l1_sampling_mld: 0.10
  scale_dwscaling_sst: 1.
  scale_dwscaling_mld: 1.
  remove_climatology: false
  climatology_spatial_pooling: 40
  use_only_climatology: 0.
  resize_factor: ${datamodule.resize_factor}
datamodule:
  aug_train_data: True 
  resize_factor: ??
  dl_kwargs:
    batch_size: ??
defaults:
  - /xp/ronan/base_xp_mld
  - /splits/dc_boost_swot@datamodule
  #- /xp/xp_aug/aug/with_aug_state_mld
  - /xp/xp_aug/aug/with_mm_aug_state_mld
  - /xp/xp_aug/dl/d240_p240x5_s240x1
  - /xp/xp_aug/sst/with_sst
  - /xp/xp_aug/loss/map
  - /xp/xp_aug/train_strat/const_lr_ngrad_5_3cas
  - _self_ 
