# @package _global_

# Ici tu peux surcharger les parties de la config que tu veux sans impacter les autres, par exemple:

entrypoint:
   weights_save_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GF_noDUACS40x240_ChckPt-wSST-hydra-exp/'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GF_noDUACS40x240_ChckPt-wSST-hydra-exp/version_146/checkpoints/modelUVwSSTGF_woDUACS-unet1_050-augdata-dws02-augstate-dT07-sstobs-nolinear-tanh-bn_20-nowgeo-nodivstrain-grad_05_03_150-epoch=122-val_loss=1.5874.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GF_noDUACS40x240_ChckPt-wSST-hydra-exp/version_146/checkpoints/modelUVwSSTGF_woDUACS-unet1_050-augdata-dws02-augstate-dT21-sstobs-nolinear-tanh-bn_20-nowgeo-nodivstrain-grad_05_03_150-epoch=93-val_loss=2.0468.ckpt'
   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_GF_noDUACS40x240_ChckPt-wSST-hydra-exp/version_148/checkpoints/modelUVwSSTGF_woDUACS-unet1_050-augdata-dws02-augstate-dT11-nowgeo-nodivstrain-grad_05_03_150-epoch=15-val_loss=2.6993.ckpt'
params:
  flag_update_training_config: False # True # 
  sst_model: 'nolinear-tanh-bn'#'nolinear-tanh-bn-att'#''linear-bn'#'linear' #
  k_n_grad: 3
  n_grad: 5
  dT: 11
  DimAE: 50
  dim_obs_sst_feat: 20
  dim_grad_solver: 150
  phi_param: 'unet1'#'unet-std'#
  ckpt_name: 'modelUVwSSTGF_woDUACS-{epoch:02d}-{val_loss:.4f}' #'modelUVwSSTGF-{epoch:02d}-{val_loss:.4f}'
  use_sst_obs: False # 
  use_sst_state: True # False
  patch_weight:
    _target_: lit_model_uv_wo_duacs.get_cropped_hanning_mask
    patch_size: ${datamodule.slice_win}
    crop:
      time: 1
  val_diag_freq: 5 
  padding_mode: reflect
  residual_wrt_geo_velocities: 0 #False #
  type_div_train_loss: 1
  alpha_mse_ssh: 50. # loss
  alpha_mse_gssh: 1000.
  alpha_mse_uv: 50.
  alpha_mse_uv_geo: 25.
  alpha_mse_div: 0. # 1000. #500. # 100. 
  alpha_mse_strain: 0. #1000.
  sig_filter_div: 1.
  norm_obs: l2
  norm_prior: l2
  sampling_model: 'sampling-from-sst'
  nb_feat_sampling_operator: 0
  alpha_sampling_uv: 10.
  thr_l1_sampling_uv: 0.10
  scale_dwscaling : 2.
datamodule:
  aug_train_data: True  
defaults:
  - /xp/ronan/base_xp_uv_wo_duacs
  - /splits/dc_boost_swot@datamodule
#  - /xp/xp_aug/aug/with_aug_state_uv_wo_duacs
  - /xp/xp_aug/aug/with_mm_aug_state_uv_wo_duacs
  - /xp/xp_aug/dl/d240_p240x5_s240x1
  - /xp/xp_aug/sst/with_sst
  - /xp/xp_aug/loss/map
  - /xp/xp_aug/train_strat/const_lr_ngrad_5_3cas
  - _self_ 
