# @package _global_

# Ici tu peux surcharger les parties de la config que tu veux sans impacter les autres, par exemple:

entrypoint:
   weights_save_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/SLANATL60_GFMMexp240x240_ChckPt-wSST-hydra-exp/'
   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/SLANATL60_GFMMexp240x240_ChckPt-wSST-hydra-exp/version_38/checkpoints/modelSLAwSSTGF-unet1_050-augdata-augstate-dT07-sstobs-nolinear-tanh-bn_20-grad_05_03_150-epoch=23-val_loss=0.2122.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/SLANATL60_GFMMexp240x240_ChckPt-wSST-hydra-exp/version_24/checkpoints/modelSLAwSSTGF-unet1_050-augdata-augstate-dT07-sstobs-nolinear-tanh-bn_20-grad_05_03_150-epoch=02-val_loss=0.2179.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/SLANATL60_GFMMexp240x240_ChckPt-wSST-hydra-exp/version_15/checkpoints/modelSLAwSSTGF-unet1_050-augdata-augstate-dT07-sstobs-linear_02-grad_05_03_150-epoch=141-val_loss=0.2899.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/SLANATL60_GFMMexp240x240_ChckPt-wSST-hydra-exp/version_20/checkpoints/modelSLAwSSTGF-unet1_050-augdata-augstate-dT07-sstobs-nolinear-tanh-bn_05-grad_05_03_150-epoch=134-val_loss=0.2658.ckpt'
   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/SLANATL60_GFMMexp240x240_ChckPt-wSST-hydra-exp/version_20/checkpoints/modelSLAwSSTGF-unet1_050-augdata-augstate-dT07-sstobs-nolinear-tanh-bn_10-grad_05_03_150-epoch=124-val_loss=0.2444.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/SLANATL60_GFMMexp240x240_ChckPt-wSST-hydra-exp/version_21/checkpoints/modelSLAwSSTGF-unet1_050-augdata-augstate-dT07-sstobs-nolinear-tanh-bn_20-grad_05_03_150-epoch=121-val_loss=0.2291.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/SLANATL60_GFMMexp240x240_ChckPt-wSST-hydra-exp/version_14/checkpoints/modelSLAwSSTGF-unet1_050-augdata-augstate-sstobs-nolinear-tanh-bn_10-grad_05_03_150-epoch=85-val_loss=0.2202.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/SLANATL60_GFMMexp240x240_ChckPt-wSST-hydra-exp/version_9/checkpoints/modelSLAwSSTGF-unet1_50-nolin-tanh-bn_10-grad05_03_150_050-augdata-augstate-sstobs-nolinear-tanh-bn_10-grad_05_03_150-epoch=114-val_loss=0.2307.ckpt'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/SLANATL60_GFMMexp240x240_ChckPt-wSST-hydra-exp/version_6/checkpoints/modelSLAwSSTGF-unet1_050-augdata-augstate-augstatesstobs-linear-bn_01-grad_05_03_150-epoch=134-val_loss=0.2951.ckpt'
# Et là tu charges la config d'où tu veux partir:

params:
  sst_model: 'nolinear-tanh-bn'# 'linear'#'linear-bn'#
  patch_weight:
    _target_: lit_model_augstate.get_constant_crop#lit_model_augstate.get_cropped_hanning_mask
    patch_size: ${datamodule.slice_win}
    crop:
      time: 3
  k_n_grad: 3
  n_grad: 5
  dT: 7
  DimAE: 50
  dim_obs_sst_feat: 20
  dim_grad_solver: 150
  save_rec_netcdf: True
  sig_filter_laplacian: 1.
  path_save_netcdf: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/SLANATL60_GFMMexp240x240_ChckPt-wSST-hydra-exp/'
  ckpt_name: 'modelSLAwSSTGF-unet1-{epoch:02d}-{val_loss:.4f}'
defaults:
#- /xp/xp_aug/xp_ronan/full_core_hanning_sst
- /xp/xp_aug/xp_repro/full_core_sst
- _self_