_target_: hydra_main.FourDVarNetHydraRunner.test
entrypoint :
  ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/SLANATL60_GFMMexp240x240_ChckPt-wSST-hydra-exp/version_2/checkpoints/modelSLAwSSTGF-linear-bn-epoch=59-val_loss=0.3856.ckpt'

defaults:
- /params: sla_gf_hal
- /domain@datamodule.dim_range: gf
- _self_