# @package _global_

xp_name: xp_oi_full_resolution #_agran

params:
  files_cfg:
    obs_mask_path: ${file_paths.pseudo_obs}
    obs_mask_var: ssh_mod
    gt_path: ${file_paths.natl_ssh_daily}
    gt_var: ssh
  model: 4dvarnet_OI
  k_n_grad: 3
  val_diag_freq: 5 
  n_grad: 5
  dT: 29
  shape_data: 
    - ${datamodule.slice_win.time}
    - ${datamodule.slice_win.lon}
    - ${datamodule.slice_win.lat}
  shape_state:
    - ${datamodule.slice_win.time}
    - ${datamodule.slice_win.lon}
    - ${datamodule.slice_win.lat}
  dW: 3
  dW2: 1
  sS: 4
  stochastic: false
  animate: false
  UsePriodicBoundary: false
  nbBlocks: 1
  DimAE: 50
  dim_grad_solver: 150
  dropout: 0.25
  dropout_phi_r: 0.0
  padding_mode: reflect
  alpha_mse_ssh: 50. # loss
  alpha_mse_gssh: 1000.  # loss
  alpha_proj: 0.5
  alpha_sr: 0.5
  alpha_lr: 0.5
  automatic_optimization: true
  ckpt_name: 'modelCalSLAInterpGF-{epoch:02d}-{val_loss:.4f}'
  norm_obs: l2
  norm_prior: l2
  patch_weight:
    crop:
      time: 3
  median_filter_width: 1
  save_outputs_path: ${oc.select:entrypoint.save_outputs_path, null}

lit_mod_cls: lit_model_AT.LitModelOI

datamodule:
  _target_: datamodule_AT.FourDVarNetDataModule
  obs_mask_path: ${params.files_cfg.obs_mask_path}
  obs_mask_var: ${params.files_cfg.obs_mask_var}
  gt_path: ${params.files_cfg.gt_path}
  gt_var: ${params.files_cfg.gt_var}
  resolution: 1/20
  resize_factor: 1 #4
  dl_kwargs:
    batch_size: 2
    num_workers: 2

logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: .
  name: null
  default_hp_metric: False


defaults:
  - /splits/dc_boost_swot@datamodule
  - /xp/baseline/aug/without_aug_state
  - /xp/baseline/dl/d240_p240x5_s240x1
  - /xp/baseline/sst/without_sst
  - /xp/baseline/loss/map
  - /xp/baseline/train_strat/const_lr_ngrad_5_3cas
  - _self_ 
