#~ python hydra_main.py file_paths=chloro/patch50 xp=cdorff/chloro/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=12.6326.ckpt' +backend=slurm_1x1 -m
#~ python hydra_main.py file_paths=chloro/patch50 xp=cdorff/chloro/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=176-val_loss\=12.5115.ckpt' +backend=slurm_1x1 -m
#~ python hydra_main.py file_paths=chloro/patch50 xp=cdorff/chloro/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=53-val_loss\=37.7404.ckpt' +backend=slurm_1x1 -m
#~ python hydra_main.py file_paths=chloro/patch50 xp=cdorff/chloro/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=194-val_loss\=33.7891.ckpt' +backend=slurm_1x1 -m
#~ python hydra_main.py file_paths=turbidity_bbp/patch50 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=18.0826.ckpt' +backend=slurm_1x1 -m
#~ python hydra_main.py file_paths=turbidity_bbp/patch50 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=18.1953.ckpt' +backend=slurm_1x1 -m
#~ python hydra_main.py file_paths=turbidity_bbp/patch50 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=192-val_loss\=48.6196.ckpt' +backend=slurm_1x1 -m
#~ python hydra_main.py file_paths=turbidity_bbp/patch50 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=174-val_loss\=50.6258.ckpt' +backend=slurm_1x1 -m



#~ python hydra_main.py file_paths=chloro/patch10/r0 xp=cdorff/chloro/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=12.6326.ckpt' +backend=slurm_1x1 -m
#~ python hydra_main.py file_paths=chloro/patch10/r1 xp=cdorff/chloro/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=12.6326.ckpt' +backend=slurm_1x1 -m
#~ python hydra_main.py file_paths=chloro/patch10/r2 xp=cdorff/chloro/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=12.6326.ckpt' +backend=slurm_1x1 -m
#~ python hydra_main.py file_paths=chloro/patch10/r3 xp=cdorff/chloro/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=12.6326.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=chloro/patch10/r4 xp=cdorff/chloro/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=12.6326.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=chloro/patch10/r5 xp=cdorff/chloro/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=12.6326.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=chloro/patch10/r6 xp=cdorff/chloro/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=12.6326.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=chloro/patch10/r7 xp=cdorff/chloro/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=12.6326.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=chloro/patch10/r8 xp=cdorff/chloro/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=12.6326.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=chloro/patch10/r9 xp=cdorff/chloro/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=12.6326.ckpt' +backend=slurm_1x1 -m

#~ python hydra_main.py file_paths=chloro/patch10/r0 xp=cdorff/chloro/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=176-val_loss\=12.5115.ckpt' +backend=slurm_1x1 -m
#~ python hydra_main.py file_paths=chloro/patch10/r1 xp=cdorff/chloro/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=176-val_loss\=12.5115.ckpt' +backend=slurm_1x1 -m
#~ python hydra_main.py file_paths=chloro/patch10/r2 xp=cdorff/chloro/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=176-val_loss\=12.5115.ckpt' +backend=slurm_1x1 -m
#~ python hydra_main.py file_paths=chloro/patch10/r3 xp=cdorff/chloro/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=176-val_loss\=12.5115.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=chloro/patch10/r4 xp=cdorff/chloro/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=176-val_loss\=12.5115.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=chloro/patch10/r5 xp=cdorff/chloro/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=176-val_loss\=12.5115.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=chloro/patch10/r6 xp=cdorff/chloro/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=176-val_loss\=12.5115.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=chloro/patch10/r7 xp=cdorff/chloro/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=176-val_loss\=12.5115.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=chloro/patch10/r8 xp=cdorff/chloro/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=176-val_loss\=12.5115.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=chloro/patch10/r9 xp=cdorff/chloro/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=176-val_loss\=12.5115.ckpt' +backend=slurm_1x1 -m

#~ python hydra_main.py file_paths=chloro/patch10/r0 xp=cdorff/chloro/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=53-val_loss\=37.7404.ckpt' +backend=slurm_1x1 -m
#~ python hydra_main.py file_paths=chloro/patch10/r1 xp=cdorff/chloro/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=53-val_loss\=37.7404.ckpt' +backend=slurm_1x1 -m
#~ python hydra_main.py file_paths=chloro/patch10/r2 xp=cdorff/chloro/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=53-val_loss\=37.7404.ckpt' +backend=slurm_1x1 -m
#~ python hydra_main.py file_paths=chloro/patch10/r3 xp=cdorff/chloro/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=53-val_loss\=37.7404.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=chloro/patch10/r4 xp=cdorff/chloro/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=53-val_loss\=37.7404.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=chloro/patch10/r5 xp=cdorff/chloro/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=53-val_loss\=37.7404.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=chloro/patch10/r6 xp=cdorff/chloro/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=53-val_loss\=37.7404.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=chloro/patch10/r7 xp=cdorff/chloro/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=53-val_loss\=37.7404.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=chloro/patch10/r8 xp=cdorff/chloro/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=53-val_loss\=37.7404.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=chloro/patch10/r9 xp=cdorff/chloro/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=53-val_loss\=37.7404.ckpt' +backend=slurm_1x1 -m

#~ python hydra_main.py file_paths=chloro/patch10/r0 xp=cdorff/chloro/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=194-val_loss\=33.7891.ckpt' +backend=slurm_1x1 -m
#~ python hydra_main.py file_paths=chloro/patch10/r1 xp=cdorff/chloro/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=194-val_loss\=33.7891.ckpt' +backend=slurm_1x1 -m
#~ python hydra_main.py file_paths=chloro/patch10/r2 xp=cdorff/chloro/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=194-val_loss\=33.7891.ckpt' +backend=slurm_1x1 -m
#~ python hydra_main.py file_paths=chloro/patch10/r3 xp=cdorff/chloro/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=194-val_loss\=33.7891.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=chloro/patch10/r4 xp=cdorff/chloro/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=194-val_loss\=33.7891.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=chloro/patch10/r5 xp=cdorff/chloro/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=194-val_loss\=33.7891.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=chloro/patch10/r6 xp=cdorff/chloro/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=194-val_loss\=33.7891.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=chloro/patch10/r7 xp=cdorff/chloro/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=194-val_loss\=33.7891.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=chloro/patch10/r8 xp=cdorff/chloro/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=194-val_loss\=33.7891.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=chloro/patch10/r9 xp=cdorff/chloro/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=194-val_loss\=33.7891.ckpt' +backend=slurm_1x1 -m

#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r0 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=18.0826.ckpt' +backend=slurm_1x1 -m
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r1 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=18.0826.ckpt' +backend=slurm_1x1 -m
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r2 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=18.0826.ckpt' +backend=slurm_1x1 -m
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r3 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=18.0826.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=turbidity_bbp/patch10/r4 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=18.0826.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=turbidity_bbp/patch10/r5 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=18.0826.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=turbidity_bbp/patch10/r6 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=18.0826.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=turbidity_bbp/patch10/r7 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=18.0826.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=turbidity_bbp/patch10/r8 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=18.0826.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=turbidity_bbp/patch10/r9 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=18.0826.ckpt' +backend=slurm_1x1 -m

#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r0 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=18.1953.ckpt' +backend=slurm_1x1 -m
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r1 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=18.1953.ckpt' +backend=slurm_1x1 -m
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r2 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=18.1953.ckpt' +backend=slurm_1x1 -m
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r3 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=18.1953.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=turbidity_bbp/patch10/r4 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=18.1953.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=turbidity_bbp/patch10/r5 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=18.1953.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=turbidity_bbp/patch10/r6 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=18.1953.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=turbidity_bbp/patch10/r7 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=18.1953.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=turbidity_bbp/patch10/r8 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=18.1953.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=turbidity_bbp/patch10/r9 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=18.1953.ckpt' +backend=slurm_1x1 -m

#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r0 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=192-val_loss\=48.6196.ckpt' +backend=slurm_1x1 -m
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r1 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=192-val_loss\=48.6196.ckpt' +backend=slurm_1x1 -m
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r2 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=192-val_loss\=48.6196.ckpt' +backend=slurm_1x1 -m
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r3 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=192-val_loss\=48.6196.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=turbidity_bbp/patch10/r4 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=192-val_loss\=48.6196.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=turbidity_bbp/patch10/r5 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=192-val_loss\=48.6196.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=turbidity_bbp/patch10/r6 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=192-val_loss\=48.6196.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=turbidity_bbp/patch10/r7 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=192-val_loss\=48.6196.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=turbidity_bbp/patch10/r8 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=192-val_loss\=48.6196.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=turbidity_bbp/patch10/r9 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=192-val_loss\=48.6196.ckpt' +backend=slurm_1x1 -m

#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r0 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=174-val_loss\=50.6258.ckpt' +backend=slurm_1x1 -m
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r1 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=174-val_loss\=50.6258.ckpt' +backend=slurm_1x1 -m
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r2 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=174-val_loss\=50.6258.ckpt' +backend=slurm_1x1 -m
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r3 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=174-val_loss\=50.6258.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=turbidity_bbp/patch10/r4 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=174-val_loss\=50.6258.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=turbidity_bbp/patch10/r5 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=174-val_loss\=50.6258.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=turbidity_bbp/patch10/r6 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=174-val_loss\=50.6258.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=turbidity_bbp/patch10/r7 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=174-val_loss\=50.6258.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=turbidity_bbp/patch10/r8 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=174-val_loss\=50.6258.ckpt' +backend=slurm_1x1 -m
python hydra_main.py file_paths=turbidity_bbp/patch10/r9 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=174-val_loss\=50.6258.ckpt' +backend=slurm_1x1 -m
