### Chloro. dt=29

#~ python hydra_main.py file_paths=chloro/patch50 xp=cdorff/chloro/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=12.6326.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r0 xp=cdorff/chloro/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=12.6326.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r1 xp=cdorff/chloro/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=12.6326.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r2 xp=cdorff/chloro/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=12.6326.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r3 xp=cdorff/chloro/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=12.6326.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r4 xp=cdorff/chloro/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=12.6326.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r5 xp=cdorff/chloro/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=12.6326.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r6 xp=cdorff/chloro/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=12.6326.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r7 xp=cdorff/chloro/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=12.6326.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r8 xp=cdorff/chloro/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=12.6326.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r9 xp=cdorff/chloro/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=12.6326.ckpt'

#~ python hydra_main.py file_paths=chloro/patch50 xp=cdorff/chloro/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=176-val_loss\=12.5115.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r0 xp=cdorff/chloro/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=176-val_loss\=12.5115.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r1 xp=cdorff/chloro/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=176-val_loss\=12.5115.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r2 xp=cdorff/chloro/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=176-val_loss\=12.5115.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r3 xp=cdorff/chloro/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=176-val_loss\=12.5115.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r4 xp=cdorff/chloro/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=176-val_loss\=12.5115.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r5 xp=cdorff/chloro/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=176-val_loss\=12.5115.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r6 xp=cdorff/chloro/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=176-val_loss\=12.5115.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r7 xp=cdorff/chloro/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=176-val_loss\=12.5115.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r8 xp=cdorff/chloro/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=176-val_loss\=12.5115.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r9 xp=cdorff/chloro/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=176-val_loss\=12.5115.ckpt'

#~ python hydra_main.py file_paths=chloro/patch50 xp=cdorff/chloro/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=53-val_loss\=37.7404.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r0 xp=cdorff/chloro/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=53-val_loss\=37.7404.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r1 xp=cdorff/chloro/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=53-val_loss\=37.7404.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r2 xp=cdorff/chloro/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=53-val_loss\=37.7404.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r3 xp=cdorff/chloro/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=53-val_loss\=37.7404.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r4 xp=cdorff/chloro/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=53-val_loss\=37.7404.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r5 xp=cdorff/chloro/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=53-val_loss\=37.7404.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r6 xp=cdorff/chloro/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=53-val_loss\=37.7404.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r7 xp=cdorff/chloro/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=53-val_loss\=37.7404.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r8 xp=cdorff/chloro/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=53-val_loss\=37.7404.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r9 xp=cdorff/chloro/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=53-val_loss\=37.7404.ckpt'

#~ python hydra_main.py file_paths=chloro/patch50 xp=cdorff/chloro/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=194-val_loss\=33.7891.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r0 xp=cdorff/chloro/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=194-val_loss\=33.7891.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r1 xp=cdorff/chloro/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=194-val_loss\=33.7891.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r2 xp=cdorff/chloro/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=194-val_loss\=33.7891.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r3 xp=cdorff/chloro/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=194-val_loss\=33.7891.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r4 xp=cdorff/chloro/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=194-val_loss\=33.7891.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r5 xp=cdorff/chloro/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=194-val_loss\=33.7891.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r6 xp=cdorff/chloro/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=194-val_loss\=33.7891.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r7 xp=cdorff/chloro/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=194-val_loss\=33.7891.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r8 xp=cdorff/chloro/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=194-val_loss\=33.7891.ckpt'
#~ python hydra_main.py file_paths=chloro/patch10/r9 xp=cdorff/chloro/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=194-val_loss\=33.7891.ckpt'


### Turbidity dt=29

#~ python hydra_main.py file_paths=turbidity_bbp/patch50 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=18.0826.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r0 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=18.0826.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r1 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=18.0826.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r2 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=18.0826.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r3 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=18.0826.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r4 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=18.0826.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r5 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=18.0826.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r6 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=18.0826.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r7 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=18.0826.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r8 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=18.0826.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r9 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=18.0826.ckpt'

#~ python hydra_main.py file_paths=turbidity_bbp/patch50 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=18.1953.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r0 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=18.1953.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r1 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=18.1953.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r2 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=18.1953.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r3 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=18.1953.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r4 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=18.1953.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r5 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=18.1953.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r6 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=18.1953.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r7 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=18.1953.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r8 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=18.1953.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r9 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=190-val_loss\=18.1953.ckpt'

#~ python hydra_main.py file_paths=turbidity_bbp/patch50 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=192-val_loss\=48.6196.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r0 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=192-val_loss\=48.6196.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r1 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=192-val_loss\=48.6196.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r2 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=192-val_loss\=48.6196.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r3 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=192-val_loss\=48.6196.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r4 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=192-val_loss\=48.6196.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r5 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=192-val_loss\=48.6196.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r6 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=192-val_loss\=48.6196.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r7 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=192-val_loss\=48.6196.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r8 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=192-val_loss\=48.6196.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r9 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=192-val_loss\=48.6196.ckpt'

#~ python hydra_main.py file_paths=turbidity_bbp/patch50 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=174-val_loss\=50.6258.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r0 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=174-val_loss\=50.6258.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r1 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=174-val_loss\=50.6258.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r2 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=174-val_loss\=50.6258.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r3 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=174-val_loss\=50.6258.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r4 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=174-val_loss\=50.6258.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r5 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=174-val_loss\=50.6258.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r6 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=174-val_loss\=50.6258.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r7 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=174-val_loss\=50.6258.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r8 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=174-val_loss\=50.6258.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r9 xp=cdorff/turbidity_bbp/xp_rf1_dt29_direct_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=174-val_loss\=50.6258.ckpt'

### Turbidity mvGT dt=29

#~ python hydra_main.py file_paths=turbidity_bbp/patch50 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE_mvGT entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=37.2273.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r0 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE_mvGT entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=37.2273.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r1 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE_mvGT entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=37.2273.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r2 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE_mvGT entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=37.2273.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r3 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE_mvGT entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=37.2273.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r4 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE_mvGT entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=37.2273.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r5 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE_mvGT entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=37.2273.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r6 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE_mvGT entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=37.2273.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r7 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE_mvGT entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=37.2273.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r8 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE_mvGT entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=37.2273.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r9 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE_mvGT entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=37.2273.ckpt'

#~ python hydra_main.py file_paths=turbidity_bbp/patch50 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet_mvGT entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=37.0635.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r0 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet_mvGT entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=37.0635.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r1 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet_mvGT entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=37.0635.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r2 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet_mvGT entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=37.0635.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r3 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet_mvGT entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=37.0635.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r4 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet_mvGT entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=37.0635.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r5 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet_mvGT entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=37.0635.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r6 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet_mvGT entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=37.0635.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r7 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet_mvGT entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=37.0635.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r8 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet_mvGT entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=37.0635.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r9 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet_mvGT entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=197-val_loss\=37.0635.ckpt'

### Turbidity + Chloro. joint dt=29

#~ python hydra_main.py file_paths=turbidity_bbp_chloro_joint/patch50 xp=cdorff/turbidity_bbp_chloro_joint/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=145-val_loss\=22.6361.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp_chloro_joint/patch10/r0 xp=cdorff/turbidity_bbp_chloro_joint/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=145-val_loss\=22.6361.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp_chloro_joint/patch10/r1 xp=cdorff/turbidity_bbp_chloro_joint/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=145-val_loss\=22.6361.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp_chloro_joint/patch10/r2 xp=cdorff/turbidity_bbp_chloro_joint/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=145-val_loss\=22.6361.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp_chloro_joint/patch10/r3 xp=cdorff/turbidity_bbp_chloro_joint/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=145-val_loss\=22.6361.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp_chloro_joint/patch10/r4 xp=cdorff/turbidity_bbp_chloro_joint/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=145-val_loss\=22.6361.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp_chloro_joint/patch10/r5 xp=cdorff/turbidity_bbp_chloro_joint/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=145-val_loss\=22.6361.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp_chloro_joint/patch10/r6 xp=cdorff/turbidity_bbp_chloro_joint/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=145-val_loss\=22.6361.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp_chloro_joint/patch10/r7 xp=cdorff/turbidity_bbp_chloro_joint/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=145-val_loss\=22.6361.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp_chloro_joint/patch10/r8 xp=cdorff/turbidity_bbp_chloro_joint/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=145-val_loss\=22.6361.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp_chloro_joint/patch10/r9 xp=cdorff/turbidity_bbp_chloro_joint/xp_rf1_dt29_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=145-val_loss\=22.6361.ckpt'


#~ python hydra_main.py file_paths=turbidity_bbp_chloro_joint/patch50 xp=cdorff/turbidity_bbp_chloro_joint/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=145-val_loss\=18.1115.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp_chloro_joint/patch10/r0 xp=cdorff/turbidity_bbp_chloro_joint/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=145-val_loss\=18.1115.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp_chloro_joint/patch10/r1 xp=cdorff/turbidity_bbp_chloro_joint/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=145-val_loss\=18.1115.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp_chloro_joint/patch10/r2 xp=cdorff/turbidity_bbp_chloro_joint/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=145-val_loss\=18.1115.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp_chloro_joint/patch10/r3 xp=cdorff/turbidity_bbp_chloro_joint/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=145-val_loss\=18.1115.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp_chloro_joint/patch10/r4 xp=cdorff/turbidity_bbp_chloro_joint/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=145-val_loss\=18.1115.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp_chloro_joint/patch10/r5 xp=cdorff/turbidity_bbp_chloro_joint/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=145-val_loss\=18.1115.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp_chloro_joint/patch10/r6 xp=cdorff/turbidity_bbp_chloro_joint/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=145-val_loss\=18.1115.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp_chloro_joint/patch10/r7 xp=cdorff/turbidity_bbp_chloro_joint/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=145-val_loss\=18.1115.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp_chloro_joint/patch10/r8 xp=cdorff/turbidity_bbp_chloro_joint/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=145-val_loss\=18.1115.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp_chloro_joint/patch10/r9 xp=cdorff/turbidity_bbp_chloro_joint/xp_rf1_dt29_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=145-val_loss\=18.1115.ckpt'


### Turbidity dt=7

#~ python hydra_main.py file_paths=turbidity_bbp/patch50 xp=cdorff/turbidity_bbp/xp_rf1_dt7_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=161-val_loss\=14.1621.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r0 xp=cdorff/turbidity_bbp/xp_rf1_dt7_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=161-val_loss\=14.1621.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r1 xp=cdorff/turbidity_bbp/xp_rf1_dt7_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=161-val_loss\=14.1621.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r2 xp=cdorff/turbidity_bbp/xp_rf1_dt7_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=161-val_loss\=14.1621.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r3 xp=cdorff/turbidity_bbp/xp_rf1_dt7_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=161-val_loss\=14.1621.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r4 xp=cdorff/turbidity_bbp/xp_rf1_dt7_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=161-val_loss\=14.1621.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r5 xp=cdorff/turbidity_bbp/xp_rf1_dt7_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=161-val_loss\=14.1621.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r6 xp=cdorff/turbidity_bbp/xp_rf1_dt7_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=161-val_loss\=14.1621.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r7 xp=cdorff/turbidity_bbp/xp_rf1_dt7_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=161-val_loss\=14.1621.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r8 xp=cdorff/turbidity_bbp/xp_rf1_dt7_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=161-val_loss\=14.1621.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r9 xp=cdorff/turbidity_bbp/xp_rf1_dt7_AE entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=161-val_loss\=14.1621.ckpt'

#~ python hydra_main.py file_paths=turbidity_bbp/patch50 xp=cdorff/turbidity_bbp/xp_rf1_dt7_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=104-val_loss\=15.2789.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r0 xp=cdorff/turbidity_bbp/xp_rf1_dt7_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=104-val_loss\=15.2789.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r1 xp=cdorff/turbidity_bbp/xp_rf1_dt7_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=104-val_loss\=15.2789.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r2 xp=cdorff/turbidity_bbp/xp_rf1_dt7_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=104-val_loss\=15.2789.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r3 xp=cdorff/turbidity_bbp/xp_rf1_dt7_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=104-val_loss\=15.2789.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r4 xp=cdorff/turbidity_bbp/xp_rf1_dt7_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=104-val_loss\=15.2789.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r5 xp=cdorff/turbidity_bbp/xp_rf1_dt7_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=104-val_loss\=15.2789.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r6 xp=cdorff/turbidity_bbp/xp_rf1_dt7_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=104-val_loss\=15.2789.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r7 xp=cdorff/turbidity_bbp/xp_rf1_dt7_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=104-val_loss\=15.2789.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r8 xp=cdorff/turbidity_bbp/xp_rf1_dt7_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=104-val_loss\=15.2789.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r9 xp=cdorff/turbidity_bbp/xp_rf1_dt7_Unet entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=104-val_loss\=15.2789.ckpt'


### Turbidity dt=29 AE25

#~ python hydra_main.py file_paths=turbidity_bbp/patch50 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE25 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=193-val_loss\=21.3147.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r0 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE25 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=193-val_loss\=21.3147.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r1 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE25 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=193-val_loss\=21.3147.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r2 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE25 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=193-val_loss\=21.3147.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r3 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE25 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=193-val_loss\=21.3147.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r4 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE25 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=193-val_loss\=21.3147.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r5 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE25 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=193-val_loss\=21.3147.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r6 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE25 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=193-val_loss\=21.3147.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r7 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE25 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=193-val_loss\=21.3147.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r8 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE25 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=193-val_loss\=21.3147.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r9 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE25 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=193-val_loss\=21.3147.ckpt'

#~ python hydra_main.py file_paths=turbidity_bbp/patch50 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet25 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=180-val_loss\=17.6546.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r0 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet25 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=180-val_loss\=17.6546.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r1 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet25 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=180-val_loss\=17.6546.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r2 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet25 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=180-val_loss\=17.6546.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r3 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet25 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=180-val_loss\=17.6546.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r4 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet25 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=180-val_loss\=17.6546.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r5 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet25 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=180-val_loss\=17.6546.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r6 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet25 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=180-val_loss\=17.6546.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r7 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet25 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=180-val_loss\=17.6546.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r8 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet25 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=180-val_loss\=17.6546.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r9 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet25 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=180-val_loss\=17.6546.ckpt'



### Turbidity dt=29 AE100

#~ python hydra_main.py file_paths=turbidity_bbp/patch50 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE100 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=100-val_loss\=18.1746.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r0 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE100 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=100-val_loss\=18.1746.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r1 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE100 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=100-val_loss\=18.1746.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r2 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE100 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=100-val_loss\=18.1746.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r3 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE100 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=100-val_loss\=18.1746.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r4 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE100 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=100-val_loss\=18.1746.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r5 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE100 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=100-val_loss\=18.1746.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r6 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE100 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=100-val_loss\=18.1746.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r7 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE100 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=100-val_loss\=18.1746.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r8 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE100 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=100-val_loss\=18.1746.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r9 xp=cdorff/turbidity_bbp/xp_rf1_dt29_AE100 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=100-val_loss\=18.1746.ckpt'

#~ python hydra_main.py file_paths=turbidity_bbp/patch50 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet100 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=143-val_loss\=18.7769.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r0 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet100 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=143-val_loss\=18.7769.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r1 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet100 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=143-val_loss\=18.7769.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r2 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet100 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=143-val_loss\=18.7769.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r3 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet100 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=143-val_loss\=18.7769.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r4 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet100 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=143-val_loss\=18.7769.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r5 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet100 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=143-val_loss\=18.7769.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r6 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet100 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=143-val_loss\=18.7769.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r7 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet100 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=143-val_loss\=18.7769.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r8 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet100 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=143-val_loss\=18.7769.ckpt'
#~ python hydra_main.py file_paths=turbidity_bbp/patch10/r9 xp=cdorff/turbidity_bbp/xp_rf1_dt29_Unet100 entrypoint=test entrypoint.ckpt_path='version_0/checkpoints/modelCalSLAInterpGF-epoch\=143-val_loss\=18.7769.ckpt'


### Clear unnecessary files
rm -rf dashboard/xp*/version*/val_data
rm -rf dashboard/xp*/lightning*/version*/test_data
