# @package _global_

xp_name: df_ose_gf_wosst
params:
  mode: predict
  model: 4dvarnet_OI
  files_cfg:
    oi_path: ${file_paths.oi_ose_nad_path}
    oi_var: ssh
    oi_decode: false
    obs_mask_path: ${file_paths.obs_mask_ose_nad_path}
    obs_mask_var: ssh
    obs_mask_decode: false
    gt_path: ${file_paths.gt_ose_path}
    gt_var: ssh
    gt_decode: false
    sst_path: null
    sst_var: null
    sst_decode: null
    analog_path: ${file_paths.gt_osse_path}
    analog_var: ssh
    analog_decode: true
  dT: 24
  patch_weight:
    crop:
      time: 3
  k_n_grad: 3
  n_grad: 5
  val_diag_freq: 5
  padding_mode: reflect
  alpha_mse_ssh: 50. # loss
  alpha_mse_gssh: 1000.
  norm_obs: l2
  norm_prior: l2
  shape_state:
    - ${datamodule.slice_win.time}
    - ${datamodule.slice_win.lon}
    - ${datamodule.slice_win.lat}
  shape_data:
    - ${datamodule.slice_win.time}
    - ${datamodule.slice_win.lon}
    - ${datamodule.slice_win.lat}

lit_mod_cls: ose.lit_model_OI_predict.LitModelOI_predict
datamodule:
  _target_: ose.dataloading_predict.FourDVarNetDataModule
  #predict_slices: ${splits.test_slices}
  predict_slices:
    - _target_: builtins.slice
      _args_: ['2016-12-19', '2017-02-12']
  analog_slices: 
    - _target_: builtins.slice
      _args_: ['2012-10-01', '2013-09-30']
  analog_path: ${params.files_cfg.analog_path}
  analog_var: ${params.files_cfg.analog_var}
  analog_decode: ${params.files_cfg.analog_decode}
  resize_factor: 1

defaults:
  - /xp/mbeaucha/xp_ose/base_xp
  - /splits/ose
  - /xp/baseline/aug/without_aug_state
  # - /xp/baseline/dl/d200_p200x5_s200x1
  - /xp/baseline/dl/d240_p240x5_s240x1
  - /xp/baseline/sst/without_sst
  - /xp/baseline/loss/map
  - /params/fourdvarnet_ose
  - /training/ose_predict
  - _self_ 
