# @package _global_
xp_name: ose_gf_wosst

lit_mod_cls: lit_model.LitModel

datamodule:
  dl_kwargs:
    batch_size: 2
  aug_train_data: False

params:
  files_cfg:
    oi_path: ${file_paths.oi_ose_nad_path}
    oi_var: ssh
    oi_decode: false
    obs_mask_path: ${file_paths.obs_mask_ose_nad_path}
    obs_mask_var: ssh
    obs_mask_decode: false
    gt_path: ${file_paths.gt_ose_path}
    gt_var: ssh
    gt_decode: false
    sst_path: null
    sst_var: null
    sst_decode: null
  dT: 7
  patch_weight:
    _target_: lit_model_augstate.get_constant_crop
    patch_size: ${datamodule.slice_win}
    crop:
      lat: 20
      lon: 20
      time: 2
  model: 4dvarnet
  sst: false
  k_n_grad: 3
  n_grad: 5
  val_diag_freq: 5
  padding_mode: reflect
  alpha_mse_ssh: 1. # loss
  alpha_mse_gssh: .1
  norm_obs: l2
  norm_prior: l2
  automatic_optimization: true
  supervised: false

defaults:
  - /xp/base_xp
  - /splits/ose
  - /xp/baseline/aug/with_aug_state
  - /xp/baseline/dl/d200_p200x5_s200x1
  - /params/fourdvarnet_ose
  - /training/ose
  - _self_

