# @package _global_
xp_name: ose_osse_nadswot_natl_wsst

lit_mod_cls: lit_model_sst.LitModelWithSST

datamodule:
  dl_kwargs:
    batch_size: 2
  aug_train_data: False

params:
  files_cfg:
    oi_path: ${file_paths.oi_ose_osse_nadswot_path}
    oi_var: ssh
    oi_decode: false
    obs_mask_path: ${file_paths.obs_mask_ose_osse_nadswot_path}
    obs_mask_var: ssh
    obs_mask_decode: false
    gt_path: ${file_paths.gt_ose_osse_path}
    gt_var: ssh
    gt_decode: false
    sst_path: ${file_paths.sst_ose_osse_path}
    sst_var: sst
    sst_decode: false
  dT: 7
  model: 4dvarnet_sst
  sst: true
  k_n_grad: 3
  n_grad: 5
  val_diag_freq: 5
  padding_mode: reflect
  alpha_mse_ssh: 50. 
  alpha_mse_gssh: 1000.
  norm_obs: l2
  norm_prior: l2
  automatic_optimization: true

defaults:
  - /xp/base_xp
  - /splits/ose_osse_natl
  - /xp/baseline/aug/without_aug_state
  - /xp/baseline/dl/dl_natl2
  - /params/fourdvarnet_ose
  - /training/ose
  - _self_
