# @package _global_

xp_name: osse_fp1_nad

lit_mod_cls: lit_model_augstate_fp.LitModelAugstate

params:
  files_cfg:
    oi_path: ${file_paths.oi_4nadirs_path}
    oi_var: ssh_mod
    obs_mask_path: ${file_paths.obs_mask_4nadirs_path}
    obs_mask_var: ssh_mod
    gt_path: ${file_paths.gt_path}
    gt_var: ssh
  dT: 7
  patch_weight:
    _target_: lit_model_augstate_fp.get_cropped_hanning_mask
    patch_size: ${datamodule.slice_win}
    crop:
      time: 1
  k_n_grad: 3
  n_fp: 0
  val_diag_freq: 5 
  padding_mode: reflect
  alpha_mse_ssh: 50. # loss
  alpha_mse_gssh: 1000.
  norm_obs: l2
  norm_prior: l2
  opt: 
    _target_: torch.optim.Adam
    lr: 0.
  model: 4dvarnet_fp
  resize_factor: 1
  supervised: true

datamodule:
  aug_train_data: 1

defaults:
  - /xp/base_xp
  - /splits/dc_boost_swot@datamodule
  - /xp/baseline/aug/with_aug_state
  - /xp/baseline/dl/d240_p240x5_s240x1
  - /xp/baseline/sst/without_sst
  - /xp/baseline/loss/map
  - /xp/baseline/train_strat/const_lr_ngrad_5_3cas
  - _self_ 
