# @package _global_

xp_name: baseline
params:
  dT: 7
  patch_weight:
    crop:
      time: 3
  k_n_grad: 3
  n_grad: 5
  val_diag_freq: 5 
  padding_mode: reflect
  alpha_mse_ssh: 50. # loss
  alpha_mse_gssh: 1000.
  norm_obs: l2
  norm_prior: l2

  opt: 
    _target_: torch.optim.Adam
    lr: 0.
datamodule:
  pp: std

entrypoint._target_: toto

defaults:
  - /xp/base_xp
  - /splits/dc_boost_swot@datamodule
  - /xp/baseline/aug/with_aug_state
  - /xp/baseline/dl/d240_p240x5_s240x1
  - /xp/baseline/sst/without_sst
  - /xp/baseline/loss/map
  - /xp/baseline/train_strat/const_lr_ngrad_5_3cas
  - _self_ 
