# @package _global_
xp_name: xp_litModel2
datamodule:
  dl_kwargs:
    batch_size: 2
params:
  iter_update: [0, 10, 20, 30, 40, 150, 800]
file_paths:
  natl_ssh: '/gpfsscratch/rech/yrf/uor23la/gt_gf_3.nc'
  #natl_ssh: '/gpfsstore/rech/yrf/commun/NATL60/NATL/ref_new/NATL60-CJM165_NATL_ssh_y2013.1y.nc'
  noisy_swot: '/gpfsstore/rech/yrf/commun/NATL60/NATL/data_new/dataset_nadir_0d_swot.nc'
entrypoint:
  max_epochs: 50
lit_mod_cls: lit_model_augstate.LitModelAugState
defaults:
  - /params: fourdvarnet_baseline
  - /domain@datamodule.dim_range: gf
  - /training: baseline
  - /splits@datamodule: dc_osse_gf
  - _self_

