# lat:
#   _target_: builtins.slice
#   _args_: [45., 55.]
# lon:
#   _target_: builtins.slice
#   _args_: [-19.5, -11.5]


lat:
  _target_: builtins.slice
  _args_: [33., 43.]
lon:
  _target_: builtins.slice
  _args_: [-65., -55.]

