# @package _global_

# Ici tu peux surcharger les parties de la config que tu veux sans impacter les autres, par exemple:

xp_name: uv_direct_inv
entrypoint:
   weights_save_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/SLANATL60_GFMMexp240x240_ChckPt-wSST-hydra-exp/'
params:
  path_save_netcdf: dashboard/${xp_name}/uv_direct_inv.ckpt
  k_n_grad: 3
  n_grad: 0
  dT: 7
  DimAE: 50
  dim_grad_solver: 150
  phi_param: 'unet-std'#'unet1'
  ckpt_name: 'modelSLAwSSTGF-{epoch:02d}-{val_loss:.4f}'
  patch_weight:
    _target_: lit_model_augstate.get_cropped_hanning_mask
    patch_size: ${datamodule.slice_win}
    crop:
      time: 1
  val_diag_freq: 5
  padding_mode: reflect
  alpha_mse_ssh: 50.
  alpha_mse_gssh: 1000.
  norm_obs: l2
  norm_prior: l2
datamodule:
  aug_train_data: true

defaults:
  - /xp/baseline/aug/without_aug_state
  - /xp/baseline/base_xp
  - _self_
