# @package _global_

# Ici tu peux surcharger les parties de la config que tu veux sans impacter les autres, par exemple:

xp_name: uv_eodyn
#entrypoint:
#   weights_save_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_Eodyn_ChckPt-wSST-hydra-exp/'
#   ckpt_path: '/gpfsscratch/rech/yrf/ulh44ct/NATL60_GF/UVNATL60_Eodyn_ChckPt-wSST-hydra-exp/version_14/checkpoints/modelUVwSSTGF-eodyn-unet1_050-augdata-augstate-dT07-sstobs-nolinear-tanh-bn_20-nowgeo-nodivstrain-grad_05_03_150-epoch=95-val_loss=1.4261.ckpt'
params:
  path_save_netcdf: uv_eodyn.ckpt
  flag_update_training_config: false
  sst_model: 'nolinear-tanh-bn'
  k_n_grad: 3
  n_grad: 5
  apha_grad_descent_step: 0.
  learn_fsgd_param: false
  dT: 7
  scale_dwscaling : 1.
  DimAE: 50
  dim_obs_sst_feat: 20
  dim_grad_solver: 150
  phi_param: 'unet1'#'unet-std'#
  ckpt_name: 'modelUVwSSTGF-eodyn-{epoch:02d}-{val_loss:.4f}'
  use_sst_obs: false
  use_sst_state: false
  patch_weight:
    _target_: lit_model_uv.get_cropped_hanning_mask
    patch_size: ${datamodule.slice_win}
    crop:
      time: 1
  val_diag_freq: 5
  padding_mode: reflect
  residual_wrt_geo_velocities: 0
  type_div_train_loss: 1
  alpha_mse_ssh: 50.
  alpha_mse_gssh: 0.
  alpha_mse_uv: 50.
  alpha_mse_uv_geo: 10.
  alpha_mse_div: 0.
  alpha_mse_strain: 0.
  sig_filter_div: 1.
  norm_obs: l2
  norm_prior: l2
  sampling_model: 'sampling-from-sst'
  nb_feat_sampling_operator: 0
  alpha_sampling_uv: 10.
  thr_l1_sampling_uv: 0.10
  scale_dwscaling_sst: 1.
datamodule:
  dl_kwargs:
    batch_size: 2
  aug_train_data: True
  resize_factor: 1
defaults:
  - /xp/uv/aug/with_aug_state_uv
  - /xp/uv/base_xp_uv
  - _self_
