# @package _global_

# Ici tu peux surcharger les parties de la config que tu veux sans impacter les autres, par exemple:

xp_name: uv_james_test
entrypoint:
  ckpt_path: ???
params:
  flag_update_training_config: false
  sst_model: 'nolinear-tanh-bn'
  files_cfg:
    oi_path: ${file_paths.oi_swot_4nadir}
    oi_var: ssh_mod
    obs_mask_path: ${file_paths.pseudo_obs}
    obs_mask_var: ssh_mod
    gt_path: ${file_paths.natl_ssh_daily}
    gt_var: ssh
  patch_weight:
    _target_: lit_model_uv.get_cropped_hanning_mask
    patch_size: ${datamodule.slice_win}
    crop:
      time: 3
  k_n_grad: 3
  n_grad: 5
  apha_grad_descent_step: 0.
  dT: 7
  DimAE: 50
  dim_obs_sst_feat: 2#10
  dim_grad_solver: 150
  save_rec_netcdf: true
  sig_filter_laplacian: 1.
  sig_filter_div_diag: 1.
  ckpt_name: 'modelUVwSSTGF-unet1-{epoch:02d}-{val_loss:.4f}'
datamodule:
  resize_factor: 1
defaults:
  - /xp/uv/aug/with_mm_aug_state_uv
  - /xp/uv/base_xp_uv
  - _self_
