# @package _global_

xp_name: xp_BBP_trainRand_dt15

params:
  model: 4dvarnet_OI
  dT: 15
  patch_weight:
    _target_: lit_model_augstate.get_hanning_mask
    patch_size: ${datamodule.slice_win}
    crop: 
      lat: ${div:0,${datamodule.resize_factor}}
      lon: ${div:0,${datamodule.resize_factor}}
      time: 0
  k_n_grad: 3
  n_grad: 5
  val_diag_freq: 5
  padding_mode: reflect
  alpha_mse_ssh: 50. # loss
  alpha_mse_gssh: 1000.
  norm_obs: l2
  norm_prior: l2
  post_proj: false ##########
  test_domain:
    lat:
      _target_: builtins.slice
      _args_: [41.17, 43.6]
    lon:
      _target_: builtins.slice
      _args_: [3., 6.09]
  shape_state:
    - ${datamodule.slice_win.time}
    - ${datamodule.slice_win.lon}
    - ${datamodule.slice_win.lat}
  shape_data:
    - ${datamodule.slice_win.time}
    - ${datamodule.slice_win.lon}
    - ${datamodule.slice_win.lat}
    
  animate: false
  
entrypoint:
  max_epochs: 100
  
lit_mod_cls: lit_model_turbidity.LitModelOI


datamodule:
  _target_: dataloading_rand.FourDVarNetDataModule
  
  dl_kwargs:
    batch_size: 10
    num_workers: 20

  resize_factor: 1
    
  dim_range:
    lat:
      _target_: builtins.slice
      _args_: [41.17, 43.6]
    lon:
      _target_: builtins.slice
      _args_: [3., 6.09]
      
      
  train_slices: 
    - _target_: builtins.slice
      _args_: ['2017-01-01', '2018-12-31']
      
  val_slices: 
    - _target_: builtins.slice
      _args_: ['2021-01-01', '2021-12-31']
      
  test_slices: 
    - _target_: builtins.slice
      _args_: ['2019-01-01', '2020-12-31']
      #_args_: ${adjust_testslices:['2020-01-01', '2021-12-31'],${params.dT}}
      
  oi_var: "BBP443"
  gt_var: "BBP443"
  obs_mask_var: "BBP443"

  pp: "man"
  mean: -2.628269458457458
  std:  0.2526552346645684
  
  slice_win:
    lat: ${div:240,${datamodule.resize_factor}}
    lon: ${div:240,${datamodule.resize_factor}}
    time: ${params.dT}
    
  strides: 
    lat: ${div:20,${datamodule.resize_factor}}
    lon: ${div:20,${datamodule.resize_factor}}
    time: 1
  
  
defaults:
  - /xp/base_xp
  - /splits/dc_boost_swot@datamodule
  - /xp/baseline/aug/without_aug_state
  - /xp/baseline/dl/d240_p240x5_s240x1
  - /xp/baseline/sst/without_sst
  - /xp/baseline/loss/map
  - /xp/baseline/train_strat/const_lr_ngrad_5_3cas
  - _self_ 
