# @package _global_
params:
  ckpt_name: 'modelSLAInterpGF-Exp3-{epoch:02d}-{val_loss:.2f}'
  norm_obs: 'l2'
  norm_prior: 'l2'
lit_mod_cls: lit_model.LitModel
datamodule:
  _target_: dataloading.FourDVarNetDataModule
  slice_win:
    lat: 200
    lon: 200
    time: 5
  strides:
    lat: 200
    lon: 200
    time: 1
  train_slices: 
    - _target_: builtins.slice
      _args_: ['2012-10-01', '2012-11-20']
    - _target_: builtins.slice
      _args_: ['2013-02-07', '2013-09-10']
  test_slices: 
    - _target_: builtins.slice
      _args_: ['2013-01-03', '2013-01-27']
  val_slices: 
    - _target_: builtins.slice
      _args_: ['2012-11-30', '2012-12-24']
  oi_path: ${params.files_cfg.oi_path}
  oi_var: ${params.files_cfg.oi_var}
  obs_mask_path: ${params.files_cfg.obs_mask_path}
  obs_mask_var: ${params.files_cfg.obs_mask_var}
  gt_path: ${params.files_cfg.gt_path}
  gt_var: ${params.files_cfg.gt_var}
  dl_kwargs:
    batch_size: 2
    num_workers: 2


