# @package _global_
params:
  ckpt_name: 'modelQG_{epoch:02d}-{val_loss:.2f}'
  norm_obs: 'l2'
  norm_prior: 'l2'
lit_mod_cls: oi.xp_qg.lit_model_oi_ref.LitModel
datamodule:
  _target_: oi.xp_qg.dataloading_qg.FourDVarNetDataModule
  slice_win:
    lat: 100
    lon: 100
    time: 5
  strides:
    lat: 100
    lon: 100
    time: 1
  train_slices: 
    - _target_: builtins.slice
#      _args_: ['2013-02-07', '2013-02-13']
      _args_: ['2012-10-01', '2012-11-20']
    - _target_: builtins.slice
      _args_: ['2013-02-07', '2013-09-10']
  test_slices: 
    - _target_: builtins.slice
      _args_: ['2013-01-03', '2013-01-27']
#      _args_: ['2013-01-03', '2013-01-08']
  val_slices: 
    - _target_: builtins.slice
      _args_: ['2012-11-30', '2012-12-24']
  obs_path: ${params.files_cfg.obs_path}
  obs_var: ${params.files_cfg.obs_var}
  gt_path: ${params.files_cfg.gt_path}
  gt_var: ${params.files_cfg.gt_var}
  u_path: ${params.files_cfg.u_path}
  u_var: ${params.files_cfg.u_var}
  v_path: ${params.files_cfg.v_path}
  v_var: ${params.files_cfg.v_var}
  dl_kwargs:
    batch_size: 2
    num_workers: 2
