# @package _global_
params:
  ckpt_name: 'modelOSEOSSESLAInterpGF-Exp3-{epoch:02d}-{val_loss:.2f}'
  norm_obs: 'l2'
  norm_prior: 'l2'
  n_fourdvar_iter: 2
  patch_weight:
    _target_: lit_model_augstate.get_constant_crop
    patch_size: ${datamodule.slice_win}
    crop:
      lat: 20
      lon: 20
      time: 2

lit_mod_cls: lit_model_augstate.LitModelAugstate
datamodule:
  predict_slices: ${splits.train_slices}
  analog_slices: ${splits.test_slices}
  oi_path: ${params.files_cfg.oi_path}
  oi_var: ${params.files_cfg.oi_var}
  oi_decode: ${params.files_cfg.oi_decode}
  obs_mask_path: ${params.files_cfg.obs_mask_path}
  obs_mask_var: ${params.files_cfg.obs_mask_var}
  obs_mask_decode: ${params.files_cfg.obs_mask_decode}
  gt_path: ${params.files_cfg.gt_path}
  gt_var: ${params.files_cfg.gt_var}
  gt_decode: ${params.files_cfg.gt_decode}
  sst_path: ${params.files_cfg.sst_path}
  sst_var: ${params.files_cfg.sst_var}
  sst_decode: ${params.files_cfg.sst_decode}
  dl_kwargs:
    batch_size: 2
    num_workers: 2

